runtime: python311

instance_class: F1

env_variables:
  GOOGLE_CLOUD_PROJECT: "sysdev-coursework"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
  secure: always

beta_settings:
  cloud_sql_instances: sysdev-coursework:us-central1:restaurant-db
